conventions:
  - path: Faithlife/CodingGuidelines/conventions/dotnet-common
  - path: Faithlife/CodingGuidelines/conventions/license-mit
    settings:
      copyright-holder: Ed Ball
  - path: MuchAdoNet/muchadonet.github.io/conventions/update-repo-docs
